from pydantic import BaseModel, Field
from typing import Annotated


class State(BaseModel):
    qury: str
    audio_data: bytes = Field(
        ...,
        description="Audio data in bytes format",
    )
    transcription: Annotated[
        str,
        Field(
            default="",
            description="Transcribed text from audio data",
        )
    ]
    response: Annotated[
        str,
        Field(
            default="",
            description="Response generated by the LLM based on the transcription",
        )
    ]